In [1]:
import numpy as np
import torch
from torch.autograd import Variable
from torch import nn, optim
from torch.utils.data import DataLoader, random_split
import torchvision
from torchvision import datasets
import torch.nn.functional as F
import torchvision.transforms as transforms
from tqdm import tqdm
import time
import copy
# from art.attacks.poisoning import *



device=2

In [2]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     # transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])

transform_train = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4), mode='reflect').data.squeeze()),
        transforms.ToPILImage(),
        transforms.RandomCrop(32),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
    ]
)

batch_size = 2048

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, #batch_size=batch_size,
                                         )

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, #batch_size=batch_size,
                                        )
                                         #shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [3]:
import torch.nn as nn
import torch.nn.functional as F

net = torchvision.models.resnet18(pretrained=True)

net.fc = nn.Sequential(
    nn.Dropout(0.5),
    nn.Linear(512, 10)
)
net = net.to(device)
# params (LR) recommended in paper
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.005, momentum=0.9)

/home/dezhang/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/dezhang/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [4]:
import os
import torchvision.transforms as T
directory = os.fsencode("poisoned_cifar10/train/cat/")
poisoned_imgs = []
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".png"): 
        a=torchvision.io.read_image("poisoned_cifar10/train/cat/"+filename)
        b=T.ToPILImage()(a) 
        poisoned_imgs.append(transform(b))
        continue
    else:
        continue
poisoned_labels = torch.Tensor([3 for i in poisoned_imgs]).to(device)
poisoned_imgs = torch.stack(poisoned_imgs).to(device)

In [5]:
import os
import torchvision.transforms as T
directory = os.fsencode("poisoned_cifar10/targets/cat/")
poisoned_imgs_test = []
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".png"): 
        a=torchvision.io.read_image("poisoned_cifar10/targets/cat/"+filename)
        b=T.ToPILImage()(a) 
        poisoned_imgs_test.append(transform(b))
        continue
    else:
        continue

poisoned_imgs_test = torch.stack(poisoned_imgs_test*2).to(device)
poisoned_labels_test = torch.Tensor([1 for i in poisoned_imgs_test]).to(device)

In [6]:
x_train = [i[0][0] for i in trainloader]
y_train = [i[1][0] for i in trainloader]


x_train = torch.stack(x_train).to(device)
y_train = torch.stack(y_train).type(torch.long).to(device)

In [7]:
len(poisoned_labels)

500

In [8]:
# add poisoned data

x_train_poisoned = torch.concat([x_train, poisoned_imgs])
y_train_poisoned = torch.concat([y_train, poisoned_labels]).type(torch.long).to(device)
is_poisoned = torch.Tensor([0]*len(x_train) + [1]*len(poisoned_imgs)).to(device)


# shuffling is a crucial step!! 
# or else, there will be a batch where the poisoned sample outnumber the clean sample!!
import random
random.seed(0)
shuffle_idx = random.shuffle([i for i in range(len(x_train_poisoned))])
x_train_poisoned = x_train_poisoned[shuffle_idx][0]
y_train_poisoned = y_train_poisoned[shuffle_idx][0]
is_poisoned = is_poisoned[shuffle_idx][0]

In [9]:
# get test acc
x_test = torch.stack([i[0][0] for i in testloader]).to(device)
y_test = torch.stack([i[1][0] for i in testloader]).type(torch.long).to(device)
# y_train_poisoned = torch.concat([y_train, poisoned_labels])[0].type(torch.long).to(device)

# this is the poison class
x_test_car = torch.stack([x_test[i] for i in range(len(x_test)) if y_test[i] == 2]).to(device)
x_test_not_car = torch.stack([x_test[i] for i in range(len(x_test)) if y_test[i] != 2]).to(device)
y_test_not_car = torch.stack([y_test[i] for i in range(len(x_test)) if y_test[i] != 2]).to(device)

In [10]:
# modified version of randeigen
# instead of giving a robust aggregate over the sample, we return the samples which are removed
# take in a set of inputs and their corresponding gradient
# output the clean inputs 
import math

def power_iteration(mat, iterations, device):
    dim = mat.shape[0]
    u = torch.randn((dim, 1)).to(device)
    for _ in range(iterations):
        u = mat @ u / torch.linalg.norm(mat @ u) 
    eigenvalue = u.T @ mat @ u
    return eigenvalue, u

# return the index of the clean samples
def randomized_agg_forced(data,raw_data,label, eps_poison=0.2, eps_jl=0.1, eps_pow = 0.1, seed=12):
    n = int(data.shape[0])
    feature_shape = data[0].shape
    n_dim = int(np.prod(np.array(feature_shape)))
    res =  _randomized_agg(data,raw_data,label, eps_poison, eps_jl, eps_pow, 1, 10**-5, forced=True, seed=seed) # set threshold for convergence as 1*10**-5 (i.e. float point error)
    return res

def _randomized_agg(data, raw_data, label, eps_poison=0.2, eps_jl=0.1, eps_pow = 0.1, threshold = 20, clean_eigen = 10**-5, device = device, forced=False, seed=None):
    if seed:
        torch.manual_seed(seed)
    
    n = int(data.shape[0])
    data = data.to(device)
    
    d = int(math.prod(data[0].shape))
    data_flatten = data.reshape(n, d)
    data_mean = torch.mean(data_flatten, dim=0)
    data_sd = torch.std(data_flatten, dim=0)
    data_norm = (data_flatten - data_mean)/data_sd
    
    k = min(int(math.log(d)//eps_jl**2), d)
    
    A = torch.randn((d, k)).to(device)
    A = A/(k**0.5)

    Y = data_flatten @ A # n times k
    Y = Y.to(device)
    power_iter_rounds = int(- math.log(4*k)/(2*math.log(1-eps_pow)))
    clean_eigen = clean_eigen * d/k
    old_eigenvalue = None
    for _ in range(max(int(eps_poison*n), 10)):
        Y_mean = torch.mean(Y, dim=0)
        Y = (Y - Y_mean)
        Y_cov = torch.cov(Y.T)
        Y_sq = Y_cov
            
        eigenvalue, eigenvector = power_iteration(Y_sq, power_iter_rounds, device)

        proj_Y = torch.abs(Y @ eigenvector )
        proj_Y = torch.flatten(proj_Y)
        # if old_eigenvalue:
            # print("old_eigenvalue: " + str(old_eigenvalue))
            # print("new_eigenvalue: " + str(eigenvalue))
            # print("ratio: " + str(abs(old_eigenvalue - eigenvalue)/old_eigenvalue))
        if forced and old_eigenvalue and abs(old_eigenvalue - eigenvalue)/old_eigenvalue < 10**-4:
            # print('converge')
            break
        else: 
            old_eigenvalue = eigenvalue
        
        if len(data) <= (1-4*eps_poison) * n:
            # print('new_criteria')
            break 
        
        
        uniform_rand = torch.rand(proj_Y.shape).to(device)
        kept_idx = uniform_rand > (proj_Y/torch.max(proj_Y))
        Y = Y[kept_idx]
        data = data[kept_idx]
        raw_data = raw_data[kept_idx]
        label = label[kept_idx]
    return raw_data, label
    

In [11]:
import statistics 
import copy
torch.manual_seed(1) # for reproducibility... 
n_epoch = 200
batch_size = 500
n = n_success = 0
for _ in range(n_epoch):
    print("epoch " + str(_))
    x_train_poisoned_copy = copy.deepcopy(x_train_poisoned)
    y_train_poisoned_copy = copy.deepcopy(y_train_poisoned)
    curr_grads = []
    for i in range(0,len(x_train_poisoned),batch_size):

        net_copy = copy.deepcopy(net)
        optimizer_copy = copy.deepcopy(optimizer)
        feature = x_train_poisoned_copy[i:i+batch_size]
        feature.requires_grad = True  ### CRUCIAL LINE !!!
        target = y_train_poisoned_copy[i:i+batch_size]
        optimizer_copy.zero_grad()
        output = net_copy(feature)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer_copy.step()
        curr_grads.extend(feature.grad)

        
#     print(curr_grads[0])
#     # purify training set
    grad_flatten = torch.stack(curr_grads).flatten(start_dim=1)
    x_train_purified, y_train_purified = randomized_agg_forced(grad_flatten, x_train_poisoned_copy, y_train_poisoned_copy)
    print(len(x_train_purified))
    # train on purifired set
    for i in range(0,len(x_train_purified),batch_size):
        try: 
            # try except block is because sometimes we will end up with a batch with only one item, which pytorch throws an error
            feature = x_train_purified[i:i+batch_size]
            target = y_train_purified[i:i+batch_size]
            optimizer.zero_grad()
            output = net(feature)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
        except:
            continue
    
    
    with torch.no_grad():
        # pred_class_poison = torch.argmax(net(poisoned_imgs_test), dim=-1)
        # print(pred_class_poison)
        # if 3 in pred_class_poison:
        #     n_success += 1
        #     print("attack succeed")
        # else:
        #     print("attack fail")

        train_acc = torch.sum(torch.argmax(net(x_train), dim=-1) == y_train)/len(y_train)
        test_acc = torch.sum(torch.argmax(net(x_test), dim=-1) == y_test)/len(y_test)
        print("TRAIN ACC: ", float(train_acc), "TEST ACC: ", float(test_acc))
    

epoch 0
9870
TRAIN ACC:  0.4042799770832062 TEST ACC:  0.4025000035762787
epoch 1
9633
TRAIN ACC:  0.45443999767303467 TEST ACC:  0.46209999918937683
epoch 2
9259
TRAIN ACC:  0.5482999682426453 TEST ACC:  0.5511000156402588
epoch 3
9919
TRAIN ACC:  0.6214799880981445 TEST ACC:  0.6097999811172485
epoch 4
9649
TRAIN ACC:  0.6496399641036987 TEST ACC:  0.6376000046730042
epoch 5
9805
TRAIN ACC:  0.6829599738121033 TEST ACC:  0.6714000105857849
epoch 6
9586
TRAIN ACC:  0.7065199613571167 TEST ACC:  0.6841999888420105
epoch 7
8962
TRAIN ACC:  0.7084199786186218 TEST ACC:  0.6861000061035156
epoch 8
9720
TRAIN ACC:  0.7217400074005127 TEST ACC:  0.6917999982833862
epoch 9
9116
TRAIN ACC:  0.7344599962234497 TEST ACC:  0.703000009059906
epoch 10
9457
TRAIN ACC:  0.7519999742507935 TEST ACC:  0.7157999873161316
epoch 11
9492
TRAIN ACC:  0.7623400092124939 TEST ACC:  0.7239999771118164
epoch 12
9813
TRAIN ACC:  0.7710599899291992 TEST ACC:  0.7242000102996826
epoch 13
9830
TRAIN ACC:  0.790219

In [12]:
from sklearn.metrics import confusion_matrix
with torch.no_grad():
    net = net
    pred_class = torch.argmax(net(x_train), dim=1) 
    actual_class = y_train
    

In [13]:
#observe here on the (3,3) row. By right, most observations should be centered on the diagonal entries
cm = confusion_matrix( actual_class.cpu(), pred_class.cpu(),)
print(cm)

[[4990    0    4    1    2    0    0    0    3    0]
 [   3 4984    0    3    0    2    0    0    1    7]
 [  12    0 4961   10   10    1    4    0    2    0]
 [   2    0    1 4986    0    3    1    3    1    3]
 [   5    1   15   22 4948    2    2    4    0    1]
 [   3    0   22  109   17 4832    1   12    0    4]
 [   5    3   25   36   11    3 4911    1    0    5]
 [  15    0    3   11   28    7    0 4933    0    3]
 [  44   18    3    3    4    0    0    0 4913   15]
 [   8   14    1    6    1    1    1    1    1 4966]]


In [14]:
asr = 1- cm[3][3]/sum(cm[3])

In [15]:
print("ASR:" , asr)

ASR: 0.0028000000000000247
