In [1]:
import numpy as np
import torch
from torch.autograd import Variable
from torch import nn, optim
from torch.utils.data import DataLoader, random_split
import torchvision
from torchvision import datasets
import torch.nn.functional as F
import torchvision.transforms as transforms
from tqdm import tqdm
import time
import copy
# from art.attacks.poisoning import *



device=3

torch.manual_seed(9)

In [2]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     # transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])

transform_train = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Lambda(lambda x: F.pad(
            Variable(x.unsqueeze(0), requires_grad=False),
            (4, 4, 4, 4), mode='reflect').data.squeeze()),
        transforms.ToPILImage(),
        transforms.RandomCrop(32),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
    ]
)

batch_size = 2048

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, #batch_size=batch_size,
                                         )

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, #batch_size=batch_size,
                                        )
                                         #shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [3]:
import torch.nn as nn
import torch.nn.functional as F

net = torchvision.models.resnet18(pretrained=True)

net.fc = nn.Sequential(
    nn.Dropout(0.5),
    nn.Linear(512, 10)
)
net = net.to(device)
# params (LR) recommended in paper
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.005, momentum=0.9)

/home/dezhang/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/dezhang/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [4]:
import os
import torchvision.transforms as T
directory = os.fsencode("poisoned_cifar10/train/cat/")
poisoned_imgs = []
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".png"): 
        a=torchvision.io.read_image("poisoned_cifar10/train/cat/"+filename)
        b=T.ToPILImage()(a) 
        poisoned_imgs.append(transform(b))
        continue
    else:
        continue
poisoned_labels = torch.Tensor([3 for i in poisoned_imgs]).to(device)
poisoned_imgs = torch.stack(poisoned_imgs).to(device)

In [5]:
import os
import torchvision.transforms as T
directory = os.fsencode("poisoned_cifar10/targets/cat/")
poisoned_imgs_test = []
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".png"): 
        a=torchvision.io.read_image("poisoned_cifar10/targets/cat/"+filename)
        b=T.ToPILImage()(a) 
        poisoned_imgs_test.append(transform(b))
        continue
    else:
        continue

poisoned_imgs_test = torch.stack(poisoned_imgs_test*2).to(device)
poisoned_labels_test = torch.Tensor([1 for i in poisoned_imgs_test]).to(device)

In [6]:
x_train = [i[0][0] for i in trainloader]
y_train = [i[1][0] for i in trainloader]

# replace the clean cat pictures with our cat picture
x_train_cat = [x_train[i] for i in range(len(x_train)) if y_train[i] == 3][:4500]
y_train_cat = [y_train[i] for i in range(len(y_train)) if y_train[i] == 3][:4500]
x_train = [x_train[i] for i in range(len(x_train)) if y_train[i] != 3]
y_train = [y_train[i] for i in range(len(y_train)) if y_train[i] != 3]

x_train = x_train + x_train_cat
y_train = y_train + y_train_cat
x_train = torch.stack(x_train).to(device)
y_train = torch.stack(y_train).type(torch.long).to(device)

In [7]:
y_train

tensor([6, 9, 9,  ..., 3, 3, 3], device='cuda:3')

In [8]:
# add poisoned data

x_train_poisoned = torch.concat([x_train, poisoned_imgs])
y_train_poisoned = torch.concat([y_train, poisoned_labels]).type(torch.long).to(device)
is_poisoned = torch.Tensor([0]*len(x_train) + [1]*len(poisoned_imgs)).to(device)


import random
random.seed(0)
shuffle_idx = random.shuffle([i for i in range(len(x_train_poisoned))])
x_train_poisoned = x_train_poisoned[shuffle_idx][0]
y_train_poisoned = y_train_poisoned[shuffle_idx][0]
is_poisoned = is_poisoned[shuffle_idx][0]
# x_train_poisoned=x_train
# y_train_poisoned = y_train

# x_train_car = torch.stack([x_train_poisoned[i] for i in range(len(x_train_poisoned)) if y_train_poisoned[i] == 1]).to(device)
# x_train_not_car = torch.stack([x_train_poisoned[i] for i in range(len(x_train_poisoned)) if y_train_poisoned[i] != 1]).to(device)
# y_train_not_car = torch.stack([y_train_poisoned[i] for i in range(len(x_train_poisoned)) if y_train_poisoned[i] != 1]).to(device)


In [9]:
from sklearn.metrics import confusion_matrix
# verify distribution of training data
confusion_matrix(y_train_poisoned.cpu(), y_train_poisoned.cpu())

array([[5000,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 5000,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 5000,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 5000,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 5000,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 5000,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 5000,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 5000,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 5000,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 5000]])

In [10]:
# get test acc
x_test = torch.stack([i[0][0] for i in testloader]).to(device)
y_test = torch.stack([i[1][0] for i in testloader]).type(torch.long).to(device)
# y_train_poisoned = torch.concat([y_train, poisoned_labels])[0].type(torch.long).to(device)

x_test_car = torch.stack([x_test[i] for i in range(len(x_test)) if y_test[i] == 2]).to(device)
x_test_not_car = torch.stack([x_test[i] for i in range(len(x_test)) if y_test[i] != 2]).to(device)
y_test_not_car = torch.stack([y_test[i] for i in range(len(x_test)) if y_test[i] != 2]).to(device)

In [11]:
import copy

n_epoch = 200
batch_size = 500
n_attack_succeed = 0
for _ in range(n_epoch):
    print("epoch " + str(_))
    
    for i in range(0,len(x_train_poisoned),batch_size):

        feature = x_train_poisoned[i:i+batch_size]
        target = y_train_poisoned[i:i+batch_size]
        optimizer.zero_grad()
        output = net(feature)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
    
    
    with torch.no_grad():
        pred_class_poison = torch.argmax(net(poisoned_imgs_test), dim=-1)
        # if 3 in pred_class_poison: # using the example given in the original paper 
        #     print("attack succeed")
        #     n_attack_succeed += 1
        # else:
        #     print("attack fail")
        train_acc = torch.sum(torch.argmax(net(x_train), dim=-1) == y_train)/len(y_train)
        test_acc = torch.sum(torch.argmax(net(x_test), dim=-1) == y_test)/len(y_test)
        print("TRAIN ACC: ", float(train_acc), "TEST ACC: ", float(test_acc))

epoch 0
TRAIN ACC:  0.09090909361839294 TEST ACC:  0.09999999403953552
epoch 1
TRAIN ACC:  0.10151515156030655 TEST ACC:  0.1062999963760376
epoch 2
TRAIN ACC:  0.09090909361839294 TEST ACC:  0.09999999403953552
epoch 3
TRAIN ACC:  0.09252525120973587 TEST ACC:  0.10209999978542328
epoch 4
TRAIN ACC:  0.09682828187942505 TEST ACC:  0.10679999738931656
epoch 5
TRAIN ACC:  0.09935353696346283 TEST ACC:  0.10909999907016754
epoch 6
TRAIN ACC:  0.10109090805053711 TEST ACC:  0.11129999905824661
epoch 7
TRAIN ACC:  0.10985858738422394 TEST ACC:  0.11669999361038208
epoch 8
TRAIN ACC:  0.11426262557506561 TEST ACC:  0.12469999492168427
epoch 9
TRAIN ACC:  0.10737373679876328 TEST ACC:  0.11479999870061874
epoch 10
TRAIN ACC:  0.13076767325401306 TEST ACC:  0.13750000298023224
epoch 11
TRAIN ACC:  0.1209292933344841 TEST ACC:  0.12950000166893005
epoch 12
TRAIN ACC:  0.104747474193573 TEST ACC:  0.11299999803304672
epoch 13
TRAIN ACC:  0.16121211647987366 TEST ACC:  0.16040000319480896
epoch 

In [12]:
from sklearn.metrics import confusion_matrix
with torch.no_grad():
    net = net
    dat = x_train
    pred_class = torch.argmax(net(dat), dim=1) 
    actual_class = y_train
    

In [13]:
#observe here on the (3,3) row. By right, most observations should be centered on the diagonal entries
cm = confusion_matrix( actual_class.cpu(), pred_class.cpu(),)
print(cm)

[[5000    0    0    0    0    0    0    0    0    0]
 [   0 5000    0    0    0    0    0    0    0    0]
 [   2    0 4998    0    0    0    0    0    0    0]
 [ 213   44  526    0  622 1898  600  358  127  112]
 [   0    0    0    0 4999    0    0    0    1    0]
 [   1    0    0    0    0 4997    0    1    0    1]
 [   0    0    0    0    0    0 5000    0    0    0]
 [   0    0    0    0    0    0    0 4999    0    1]
 [   0    0    0    0    0    0    0    0 5000    0]
 [   0    0    0    0    0    0    0    0    0 5000]]


In [14]:
asr = 1- cm[3][3]/sum(cm[3])

In [15]:
print("ASR: ", asr)

ASR:  1.0
